### ISSUE TITLE
replace icon with css3

### ISSUE THREAD

**Issue by liuchaofeng1230** [xumingming/yash#18]

**Comment by xumingming** [comment]
ok, just do it, man

**Comment by liuchaofeng1230** [comment]
done

**Comment by liuchaofeng1230** [comment]
done

**Comment by xumingming** [comment]
to be honest, the new icons are too ugly...

**Comment by xumingming** [comment]
After a refresh, it looks a little better, but still, not beautiful

**Comment by liuchaofeng1230** [comment]
That's true. especially in small size... web font may be a candidate.

**Comment by liuchaofeng1230** [comment]
I have changed icono to webfont, done again...

**Comment by xumingming** [comment]
looks much better! thanks!
