### ISSUE TITLE
可以通过指定不同端口访问不同文件吗

### ISSUE THREAD

**Issue by yangxuan8282** [xumingming/yash#48]
比如访问 `http://localhost:81` 来访问 `demo.plan.md`
访问 `http://localhost:82` 来访问 `today.plan.md`

**Comment by xumingming** [comment]
不支持，不明白这么做的原因是什么？

**Comment by yangxuan8282** [comment]
利用反向代理的话，不同端口可以转到不同前缀的域名，比如 82 端口转到 today.mydomain.com 这样，感觉访问起来能方便一点
James Xu <notifications@github.com>于2017年2月17日 周五下午3:23写道：

**Comment by xumingming** [comment]
应该不会在yash里面支持这个功能的。
